# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "lb1" do |lb1|
    lb01.vm.box = "ubuntu/trusty64"
    lb01.vm.hostname = "lb1"
    lb01.vm.network :private_network, ip: "10.11.11.30"
	lb01.vm.provision "shell", path: "lb1.sh"
  end

  config.vm.define "web1" do |web1|
    web01.vm.box = "ubuntu/trusty64"
    web01.vm.hostname = "web1"
    web01.vm.network :private_network, ip: "10.11.11.31"
	web01.vm.provision "shell", path: "web1.sh"
  end

  config.vm.define "web2" do |web2|
    web02.vm.box = "ubuntu/trusty64"
    web02.vm.hostname = "web2"
    web02.vm.network :private_network, ip: "10.11.11.32"
	web02.vm.provision "shell", path: "web2.sh"
  end
end
